title: RubLeo
description: Project updates and personal stuff.
url: "https://rubleo.github.io"

# Google Analytics
#google_analytics: UAâ€”XXXXXXXX-X

# Author
author:
  name:         RubLeo
  url:          https://rubleo.github.io
  #email:        mail@mail.tld

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# theme: minima
remote_theme: chesterhow/tale
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
